.class public Lorg/eclipse/jetty/deploy/graph/GraphOutputDot;
.super Ljava/lang/Object;
.source "GraphOutputDot.java"


# annotations
.annotation system Ldalvik/annotation/MemberClasses;
    value = {
        Lorg/eclipse/jetty/deploy/graph/GraphOutputDot$1;,
        Lorg/eclipse/jetty/deploy/graph/GraphOutputDot$TopNodeSort;
    }
.end annotation


# static fields
.field private static final TOPNODE:Ljava/lang/String; = "undeployed"


# direct methods
.method private constructor <init>()V
    .locals 0

    .prologue
    .line 36
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    .line 37
    return-void
.end method

.method private static toId(Lorg/eclipse/jetty/deploy/graph/Node;)Ljava/lang/CharSequence;
    .locals 6
    .param p0, "node"    # Lorg/eclipse/jetty/deploy/graph/Node;

    .prologue
    .line 139
    new-instance v1, Ljava/lang/StringBuilder;

    invoke-direct {v1}, Ljava/lang/StringBuilder;-><init>()V

    .line 141
    .local v1, "buf":Ljava/lang/StringBuilder;
    invoke-virtual {p0}, Lorg/eclipse/jetty/deploy/graph/Node;->getName()Ljava/lang/String;

    move-result-object v5

    invoke-virtual {v5}, Ljava/lang/String;->toCharArray()[C

    move-result-object v0

    .local v0, "arr$":[C
    array-length v4, v0

    .local v4, "len$":I
    const/4 v3, 0x0

    .local v3, "i$":I
    :goto_0
    if-ge v3, v4, :cond_4

    aget-char v2, v0, v3

    .line 143
    .local v2, "c":C
    invoke-static {v2}, Ljava/lang/Character;->isLetter(C)Z

    move-result v5

    if-eqz v5, :cond_1

    .line 145
    invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(C)Ljava/lang/StringBuilder;

    .line 141
    :cond_0
    :goto_1
    add-int/lit8 v3, v3, 0x1

    goto :goto_0

    .line 149
    :cond_1
    invoke-static {v2}, Ljava/lang/Character;->isDigit(C)Z

    move-result v5

    if-eqz v5, :cond_2

    .line 151
    invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(C)Ljava/lang/StringBuilder;

    goto :goto_1

    .line 155
    :cond_2
    const/16 v5, 0x20

    if-eq v2, v5, :cond_3

    const/16 v5, 0x2d

    if-eq v2, v5, :cond_3

    const/16 v5, 0x5f

    if-ne v2, v5, :cond_0

    .line 157
    :cond_3
    invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(C)Ljava/lang/StringBuilder;

    goto :goto_1

    .line 162
    .end local v2    # "c":C
    :cond_4
    return-object v1
.end method

.method public static write(Lorg/eclipse/jetty/deploy/graph/Graph;Ljava/io/File;)V
    .locals 10
    .param p0, "graph"    # Lorg/eclipse/jetty/deploy/graph/Graph;
    .param p1, "outputFile"    # Ljava/io/File;
    .annotation system Ldalvik/annotation/Throws;
        value = {
            Ljava/io/IOException;
        }
    .end annotation

    .prologue
    .line 75
    const/4 v6, 0x0

    .line 76
    .local v6, "writer":Ljava/io/FileWriter;
    const/4 v4, 0x0

    .line 80
    .local v4, "out":Ljava/io/PrintWriter;
    :try_start_0
    new-instance v7, Ljava/io/FileWriter;

    invoke-direct {v7, p1}, Ljava/io/FileWriter;-><init>(Ljava/io/File;)V
    :try_end_0
    .catchall {:try_start_0 .. :try_end_0} :catchall_1

    .line 81
    .end local v6    # "writer":Ljava/io/FileWriter;
    .local v7, "writer":Ljava/io/FileWriter;
    :try_start_1
    new-instance v5, Ljava/io/PrintWriter;

    invoke-direct {v5, v7}, Ljava/io/PrintWriter;-><init>(Ljava/io/Writer;)V
    :try_end_1
    .catchall {:try_start_1 .. :try_end_1} :catchall_2

    .line 83
    .end local v4    # "out":Ljava/io/PrintWriter;
    .local v5, "out":Ljava/io/PrintWriter;
    :try_start_2
    new-instance v8, Ljava/lang/StringBuilder;

    invoke-direct {v8}, Ljava/lang/StringBuilder;-><init>()V

    const-string v9, "// Autogenerated by "

    invoke-virtual {v8, v9}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v8

    const-class v9, Lorg/eclipse/jetty/deploy/graph/GraphOutputDot;

    invoke-virtual {v9}, Ljava/lang/Class;->getName()Ljava/lang/String;

    move-result-object v9

    invoke-virtual {v8, v9}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v8

    invoke-virtual {v8}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v8

    invoke-virtual {v5, v8}, Ljava/io/PrintWriter;->println(Ljava/lang/String;)V

    .line 84
    const-string v8, "digraph Graf {"

    invoke-virtual {v5, v8}, Ljava/io/PrintWriter;->println(Ljava/lang/String;)V

    .line 86
    invoke-static {v5}, Lorg/eclipse/jetty/deploy/graph/GraphOutputDot;->writeGraphDefaults(Ljava/io/PrintWriter;)V

    .line 87
    invoke-static {v5}, Lorg/eclipse/jetty/deploy/graph/GraphOutputDot;->writeNodeDefaults(Ljava/io/PrintWriter;)V

    .line 88
    invoke-static {v5}, Lorg/eclipse/jetty/deploy/graph/GraphOutputDot;->writeEdgeDefaults(Ljava/io/PrintWriter;)V

    .line 90
    new-instance v3, Ljava/util/TreeSet;

    new-instance v8, Lorg/eclipse/jetty/deploy/graph/GraphOutputDot$TopNodeSort;

    const/4 v9, 0x0

    invoke-direct {v8, v9}, Lorg/eclipse/jetty/deploy/graph/GraphOutputDot$TopNodeSort;-><init>(Lorg/eclipse/jetty/deploy/graph/GraphOutputDot$1;)V

    invoke-direct {v3, v8}, Ljava/util/TreeSet;-><init>(Ljava/util/Comparator;)V

    .line 91
    .local v3, "nodes":Ljava/util/Set;, "Ljava/util/Set<Lorg/eclipse/jetty/deploy/graph/Node;>;"
    invoke-virtual {p0}, Lorg/eclipse/jetty/deploy/graph/Graph;->getNodes()Ljava/util/Set;

    move-result-object v8

    invoke-interface {v3, v8}, Ljava/util/Set;->addAll(Ljava/util/Collection;)Z

    .line 93
    invoke-interface {v3}, Ljava/util/Set;->iterator()Ljava/util/Iterator;

    move-result-object v1

    .local v1, "i$":Ljava/util/Iterator;
    :goto_0
    invoke-interface {v1}, Ljava/util/Iterator;->hasNext()Z

    move-result v8

    if-eqz v8, :cond_0

    invoke-interface {v1}, Ljava/util/Iterator;->next()Ljava/lang/Object;

    move-result-object v2

    check-cast v2, Lorg/eclipse/jetty/deploy/graph/Node;

    .line 95
    .local v2, "node":Lorg/eclipse/jetty/deploy/graph/Node;
    invoke-static {v5, v2}, Lorg/eclipse/jetty/deploy/graph/GraphOutputDot;->writeNode(Ljava/io/PrintWriter;Lorg/eclipse/jetty/deploy/graph/Node;)V
    :try_end_2
    .catchall {:try_start_2 .. :try_end_2} :catchall_0

    goto :goto_0

    .line 107
    .end local v1    # "i$":Ljava/util/Iterator;
    .end local v2    # "node":Lorg/eclipse/jetty/deploy/graph/Node;
    .end local v3    # "nodes":Ljava/util/Set;, "Ljava/util/Set<Lorg/eclipse/jetty/deploy/graph/Node;>;"
    :catchall_0
    move-exception v8

    move-object v4, v5

    .end local v5    # "out":Ljava/io/PrintWriter;
    .restart local v4    # "out":Ljava/io/PrintWriter;
    move-object v6, v7

    .end local v7    # "writer":Ljava/io/FileWriter;
    .restart local v6    # "writer":Ljava/io/FileWriter;
    :goto_1
    invoke-static {v4}, Lorg/eclipse/jetty/util/IO;->close(Ljava/io/Writer;)V

    .line 108
    invoke-static {v6}, Lorg/eclipse/jetty/util/IO;->close(Ljava/io/Writer;)V

    throw v8

    .line 98
    .end local v4    # "out":Ljava/io/PrintWriter;
    .end local v6    # "writer":Ljava/io/FileWriter;
    .restart local v1    # "i$":Ljava/util/Iterator;
    .restart local v3    # "nodes":Ljava/util/Set;, "Ljava/util/Set<Lorg/eclipse/jetty/deploy/graph/Node;>;"
    .restart local v5    # "out":Ljava/io/PrintWriter;
    .restart local v7    # "writer":Ljava/io/FileWriter;
    :cond_0
    :try_start_3
    invoke-virtual {p0}, Lorg/eclipse/jetty/deploy/graph/Graph;->getEdges()Ljava/util/Set;

    move-result-object v8

    invoke-interface {v8}, Ljava/util/Set;->iterator()Ljava/util/Iterator;

    move-result-object v1

    :goto_2
    invoke-interface {v1}, Ljava/util/Iterator;->hasNext()Z

    move-result v8

    if-eqz v8, :cond_1

    invoke-interface {v1}, Ljava/util/Iterator;->next()Ljava/lang/Object;

    move-result-object v0

    check-cast v0, Lorg/eclipse/jetty/deploy/graph/Edge;

    .line 100
    .local v0, "edge":Lorg/eclipse/jetty/deploy/graph/Edge;
    invoke-static {v5, v0}, Lorg/eclipse/jetty/deploy/graph/GraphOutputDot;->writeEdge(Ljava/io/PrintWriter;Lorg/eclipse/jetty/deploy/graph/Edge;)V

    goto :goto_2

    .line 103
    .end local v0    # "edge":Lorg/eclipse/jetty/deploy/graph/Edge;
    :cond_1
    const-string v8, "}"

    invoke-virtual {v5, v8}, Ljava/io/PrintWriter;->println(Ljava/lang/String;)V
    :try_end_3
    .catchall {:try_start_3 .. :try_end_3} :catchall_0

    .line 107
    invoke-static {v5}, Lorg/eclipse/jetty/util/IO;->close(Ljava/io/Writer;)V

    .line 108
    invoke-static {v7}, Lorg/eclipse/jetty/util/IO;->close(Ljava/io/Writer;)V

    .line 110
    return-void

    .line 107
    .end local v1    # "i$":Ljava/util/Iterator;
    .end local v3    # "nodes":Ljava/util/Set;, "Ljava/util/Set<Lorg/eclipse/jetty/deploy/graph/Node;>;"
    .end local v5    # "out":Ljava/io/PrintWriter;
    .end local v7    # "writer":Ljava/io/FileWriter;
    .restart local v4    # "out":Ljava/io/PrintWriter;
    .restart local v6    # "writer":Ljava/io/FileWriter;
    :catchall_1
    move-exception v8

    goto :goto_1

    .end local v6    # "writer":Ljava/io/FileWriter;
    .restart local v7    # "writer":Ljava/io/FileWriter;
    :catchall_2
    move-exception v8

    move-object v6, v7

    .end local v7    # "writer":Ljava/io/FileWriter;
    .restart local v6    # "writer":Ljava/io/FileWriter;
    goto :goto_1
.end method

.method private static writeEdge(Ljava/io/PrintWriter;Lorg/eclipse/jetty/deploy/graph/Edge;)V
    .locals 4
    .param p0, "out"    # Ljava/io/PrintWriter;
    .param p1, "edge"    # Lorg/eclipse/jetty/deploy/graph/Edge;

    .prologue
    .line 114
    invoke-virtual {p0}, Ljava/io/PrintWriter;->println()V

    .line 115
    const-string v0, "  // Edge"

    invoke-virtual {p0, v0}, Ljava/io/PrintWriter;->println(Ljava/lang/String;)V

    .line 116
    const-string v0, "  \"%s\" -> \"%s\" [%n"

    const/4 v1, 0x2

    new-array v1, v1, [Ljava/lang/Object;

    const/4 v2, 0x0

    invoke-virtual {p1}, Lorg/eclipse/jetty/deploy/graph/Edge;->getFrom()Lorg/eclipse/jetty/deploy/graph/Node;

    move-result-object v3

    invoke-static {v3}, Lorg/eclipse/jetty/deploy/graph/GraphOutputDot;->toId(Lorg/eclipse/jetty/deploy/graph/Node;)Ljava/lang/CharSequence;

    move-result-object v3

    aput-object v3, v1, v2

    const/4 v2, 0x1

    invoke-virtual {p1}, Lorg/eclipse/jetty/deploy/graph/Edge;->getTo()Lorg/eclipse/jetty/deploy/graph/Node;

    move-result-object v3

    invoke-static {v3}, Lorg/eclipse/jetty/deploy/graph/GraphOutputDot;->toId(Lorg/eclipse/jetty/deploy/graph/Node;)Ljava/lang/CharSequence;

    move-result-object v3

    aput-object v3, v1, v2

    invoke-virtual {p0, v0, v1}, Ljava/io/PrintWriter;->printf(Ljava/lang/String;[Ljava/lang/Object;)Ljava/io/PrintWriter;

    .line 117
    const-string v0, "    arrowtail=none,"

    invoke-virtual {p0, v0}, Ljava/io/PrintWriter;->println(Ljava/lang/String;)V

    .line 118
    const-string v0, "    arrowhead=normal"

    invoke-virtual {p0, v0}, Ljava/io/PrintWriter;->println(Ljava/lang/String;)V

    .line 119
    const-string v0, "  ];"

    invoke-virtual {p0, v0}, Ljava/io/PrintWriter;->println(Ljava/lang/String;)V

    .line 120
    return-void
.end method

.method private static writeEdgeDefaults(Ljava/io/PrintWriter;)V
    .locals 1
    .param p0, "out"    # Ljava/io/PrintWriter;

    .prologue
    .line 167
    invoke-virtual {p0}, Ljava/io/PrintWriter;->println()V

    .line 168
    const-string v0, "  // Edge Defaults "

    invoke-virtual {p0, v0}, Ljava/io/PrintWriter;->println(Ljava/lang/String;)V

    .line 169
    const-string v0, "  edge ["

    invoke-virtual {p0, v0}, Ljava/io/PrintWriter;->println(Ljava/lang/String;)V

    .line 170
    const-string v0, "    arrowsize=\"0.8\","

    invoke-virtual {p0, v0}, Ljava/io/PrintWriter;->println(Ljava/lang/String;)V

    .line 171
    const-string v0, "    fontsize=\"11\""

    invoke-virtual {p0, v0}, Ljava/io/PrintWriter;->println(Ljava/lang/String;)V

    .line 172
    const-string v0, "  ];"

    invoke-virtual {p0, v0}, Ljava/io/PrintWriter;->println(Ljava/lang/String;)V

    .line 173
    return-void
.end method

.method private static writeGraphDefaults(Ljava/io/PrintWriter;)V
    .locals 1
    .param p0, "out"    # Ljava/io/PrintWriter;

    .prologue
    .line 177
    invoke-virtual {p0}, Ljava/io/PrintWriter;->println()V

    .line 178
    const-string v0, "  // Graph Defaults "

    invoke-virtual {p0, v0}, Ljava/io/PrintWriter;->println(Ljava/lang/String;)V

    .line 179
    const-string v0, "  graph ["

    invoke-virtual {p0, v0}, Ljava/io/PrintWriter;->println(Ljava/lang/String;)V

    .line 180
    const-string v0, "    bgcolor=\"#ffffff\","

    invoke-virtual {p0, v0}, Ljava/io/PrintWriter;->println(Ljava/lang/String;)V

    .line 181
    const-string v0, "    fontname=\"Helvetica\","

    invoke-virtual {p0, v0}, Ljava/io/PrintWriter;->println(Ljava/lang/String;)V

    .line 182
    const-string v0, "    fontsize=\"11\","

    invoke-virtual {p0, v0}, Ljava/io/PrintWriter;->println(Ljava/lang/String;)V

    .line 183
    const-string v0, "    label=\"Graph\","

    invoke-virtual {p0, v0}, Ljava/io/PrintWriter;->println(Ljava/lang/String;)V

    .line 184
    const-string v0, "    labeljust=\"l\","

    invoke-virtual {p0, v0}, Ljava/io/PrintWriter;->println(Ljava/lang/String;)V

    .line 185
    const-string v0, "    rankdir=\"TD\""

    invoke-virtual {p0, v0}, Ljava/io/PrintWriter;->println(Ljava/lang/String;)V

    .line 186
    const-string v0, "  ];"

    invoke-virtual {p0, v0}, Ljava/io/PrintWriter;->println(Ljava/lang/String;)V

    .line 187
    return-void
.end method

.method private static writeNode(Ljava/io/PrintWriter;Lorg/eclipse/jetty/deploy/graph/Node;)V
    .locals 5
    .param p0, "out"    # Ljava/io/PrintWriter;
    .param p1, "node"    # Lorg/eclipse/jetty/deploy/graph/Node;

    .prologue
    const/4 v4, 0x1

    const/4 v3, 0x0

    .line 124
    invoke-virtual {p0}, Ljava/io/PrintWriter;->println()V

    .line 125
    const-string v0, "  // Node"

    invoke-virtual {p0, v0}, Ljava/io/PrintWriter;->println(Ljava/lang/String;)V

    .line 126
    const-string v0, "  \"%s\" [%n"

    new-array v1, v4, [Ljava/lang/Object;

    invoke-static {p1}, Lorg/eclipse/jetty/deploy/graph/GraphOutputDot;->toId(Lorg/eclipse/jetty/deploy/graph/Node;)Ljava/lang/CharSequence;

    move-result-object v2

    aput-object v2, v1, v3

    invoke-virtual {p0, v0, v1}, Ljava/io/PrintWriter;->printf(Ljava/lang/String;[Ljava/lang/Object;)Ljava/io/PrintWriter;

    .line 127
    const-string v0, "    label=\"%s\",%n"

    new-array v1, v4, [Ljava/lang/Object;

    invoke-virtual {p1}, Lorg/eclipse/jetty/deploy/graph/Node;->getName()Ljava/lang/String;

    move-result-object v2

    aput-object v2, v1, v3

    invoke-virtual {p0, v0, v1}, Ljava/io/PrintWriter;->printf(Ljava/lang/String;[Ljava/lang/Object;)Ljava/io/PrintWriter;

    .line 128
    invoke-virtual {p1}, Lorg/eclipse/jetty/deploy/graph/Node;->getName()Ljava/lang/String;

    move-result-object v0

    const-string v1, "ed"

    invoke-virtual {v0, v1}, Ljava/lang/String;->endsWith(Ljava/lang/String;)Z

    move-result v0

    if-eqz v0, :cond_0

    .line 130
    const-string v0, "    color=\"#ddddff\","

    invoke-virtual {p0, v0}, Ljava/io/PrintWriter;->println(Ljava/lang/String;)V

    .line 131
    const-string v0, "    style=filled,"

    invoke-virtual {p0, v0}, Ljava/io/PrintWriter;->println(Ljava/lang/String;)V

    .line 133
    :cond_0
    const-string v0, "    shape=box"

    invoke-virtual {p0, v0}, Ljava/io/PrintWriter;->println(Ljava/lang/String;)V

    .line 134
    const-string v0, "  ];"

    invoke-virtual {p0, v0}, Ljava/io/PrintWriter;->println(Ljava/lang/String;)V

    .line 135
    return-void
.end method

.method private static writeNodeDefaults(Ljava/io/PrintWriter;)V
    .locals 1
    .param p0, "out"    # Ljava/io/PrintWriter;

    .prologue
    .line 191
    invoke-virtual {p0}, Ljava/io/PrintWriter;->println()V

    .line 192
    const-string v0, "  // Node Defaults "

    invoke-virtual {p0, v0}, Ljava/io/PrintWriter;->println(Ljava/lang/String;)V

    .line 193
    const-string v0, "  node ["

    invoke-virtual {p0, v0}, Ljava/io/PrintWriter;->println(Ljava/lang/String;)V

    .line 194
    const-string v0, "    fontname=\"Helvetica\","

    invoke-virtual {p0, v0}, Ljava/io/PrintWriter;->println(Ljava/lang/String;)V

    .line 195
    const-string v0, "    fontsize=\"11\","

    invoke-virtual {p0, v0}, Ljava/io/PrintWriter;->println(Ljava/lang/String;)V

    .line 196
    const-string v0, "    shap=\"box\""

    invoke-virtual {p0, v0}, Ljava/io/PrintWriter;->println(Ljava/lang/String;)V

    .line 197
    const-string v0, "  ];"

    invoke-virtual {p0, v0}, Ljava/io/PrintWriter;->println(Ljava/lang/String;)V

    .line 198
    return-void
.end method
